use std::fs;
use std::path::{Path, PathBuf};

use crate::error::{OslError, Result};

pub const DEFAULT_INTERVAL: u64 = 60;

pub struct AutostartConfig {
    pub osl_exe: PathBuf,
    pub vault: PathBuf,
    pub paths: Vec<PathBuf>,
    pub interval: u64,
}

impl AutostartConfig {
    pub fn new(paths: &[PathBuf], vault: &Path) -> Result<Self> {
        let osl_exe = std::env::current_exe()
            .map_err(|e| OslError::Usage(format!("cannot locate osl executable: {e}")))?;

        let vault = if vault.is_absolute() {
            vault.to_path_buf()
        } else {
            std::env::current_dir()
                .map_err(|e| OslError::Usage(format!("cannot determine current directory: {e}")))?
                .join(vault)
        };

        let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        let paths: Vec<PathBuf> = paths
            .iter()
            .map(|p| {
                if p.is_absolute() {
                    p.clone()
                } else {
                    cwd.join(p)
                }
            })
            .collect();

        Ok(Self {
            osl_exe,
            vault,
            paths,
            interval: DEFAULT_INTERVAL,
        })
    }
}

fn render_systemd_unit(cfg: &AutostartConfig) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let exe = shell_quote(&cfg.osl_exe.to_string_lossy());
    let vault = shell_quote(&cfg.vault.to_string_lossy());

    let mut exec = format!(
        r#"ExecStart={} watch --interval {} --vault {}"#,
        exe, cfg.interval, vault
    );
    for path in &cfg.paths {
        exec.push(' ');
        exec.push_str(&shell_quote(&path.to_string_lossy()));
    }

    format!(
        r#"# Generated by osl {}. Do not edit manually.
[Unit]
Description=OpenSessionLog watch daemon

[Service]
Type=simple
{}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"#,
        version, exec
    )
}

#[allow(dead_code)]
fn render_launchd_plist(cfg: &AutostartConfig) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let mut args = String::new();

    args.push_str(&format!(
        "        <string>{}</string>\n",
        xml_escape(&cfg.osl_exe.to_string_lossy())
    ));
    args.push_str("        <string>watch</string>\n");
    args.push_str("        <string>--interval</string>\n");
    args.push_str(&format!("        <string>{}</string>\n", cfg.interval));
    args.push_str("        <string>--vault</string>\n");
    args.push_str(&format!(
        "        <string>{}</string>\n",
        xml_escape(&cfg.vault.to_string_lossy())
    ));
    for path in &cfg.paths {
        args.push_str(&format!(
            "        <string>{}</string>\n",
            xml_escape(&path.to_string_lossy())
        ));
    }

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by osl {}. Do not edit manually. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.opensessionlog.osl-watch</string>
    <key>ProgramArguments</key>
    <array>
{}    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
</dict>
</plist>
"#,
        version, args
    )
}

#[allow(dead_code)]
fn render_schtasks_xml(cfg: &AutostartConfig) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let exe = cfg.osl_exe.to_string_lossy();
    let vault = cfg.vault.to_string_lossy();

    let command = shell_quote(&exe);
    let mut arguments = format!(
        "watch --interval {} --vault {}",
        cfg.interval,
        shell_quote(&vault)
    );
    for path in &cfg.paths {
        arguments.push(' ');
        arguments.push_str(&shell_quote(&path.to_string_lossy()));
    }

    format!(
        r#"<?xml version="1.0" encoding="UTF-16"?>
<!-- Generated by osl {}. Do not edit manually. -->
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>{}</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{}</Command>
      <Arguments>{}</Arguments>
    </Exec>
  </Actions>
</Task>
"#,
        version,
        xml_escape("OpenSessionLog watch daemon"),
        xml_escape(&command),
        xml_escape(&arguments)
    )
}

fn shell_quote(s: &str) -> String {
    if s.contains(' ') {
        format!(r#""{}""#, s)
    } else {
        s.to_string()
    }
}

#[allow(dead_code)]
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            c => out.push(c),
        }
    }
    out
}

pub fn install(paths: &[PathBuf], vault: &Path) -> Result<()> {
    let home = resolve_home()?;
    let cfg = AutostartConfig::new(paths, vault)?;
    install_with_home(&cfg, &home)
}

pub fn remove() -> Result<()> {
    let home = resolve_home()?;
    remove_with_home(&home)
}

pub fn install_with_home(cfg: &AutostartConfig, home: &Path) -> Result<()> {
    platform::install_with_home(cfg, home)
}

pub fn remove_with_home(home: &Path) -> Result<()> {
    platform::remove_with_home(home)
}

pub fn resolve_home() -> Result<PathBuf> {
    #[cfg(target_os = "windows")]
    {
        if let Some(userprofile) = std::env::var_os("USERPROFILE") {
            return Ok(PathBuf::from(userprofile));
        }
        if let Some(home) = std::env::var_os("HOME") {
            return Ok(PathBuf::from(home));
        }
        return Err(OslError::Usage(
            "could not determine home directory: set USERPROFILE or HOME".into(),
        ));
    }
    #[cfg(not(target_os = "windows"))]
    {
        if let Some(home) = std::env::var_os("HOME") {
            return Ok(PathBuf::from(home));
        }
        Err(OslError::Usage(
            "could not determine home directory: set HOME".into(),
        ))
    }
}

mod platform {
    use super::*;

    #[cfg(target_os = "linux")]
    pub fn install_with_home(cfg: &AutostartConfig, home: &Path) -> Result<()> {
        let path = home.join(".config/systemd/user/osl-watch.service");
        let existed = path.exists();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, render_systemd_unit(cfg))?;
        if existed {
            println!(
                "systemctl --user daemon-reload && systemctl --user restart osl-watch.service"
            );
        } else {
            println!(
                "systemctl --user daemon-reload && systemctl --user enable --now osl-watch.service"
            );
        }
        println!("Tip: run `loginctl enable-linger` to keep the service running after logout.");
        Ok(())
    }

    #[cfg(target_os = "linux")]
    pub fn remove_with_home(home: &Path) -> Result<()> {
        let path = home.join(".config/systemd/user/osl-watch.service");
        if path.exists() {
            fs::remove_file(&path)?;
            println!("systemctl --user disable --now osl-watch.service");
            Ok(())
        } else {
            println!("No autostart config found");
            Ok(())
        }
    }

    #[cfg(target_os = "macos")]
    pub fn install_with_home(cfg: &AutostartConfig, home: &Path) -> Result<()> {
        let path = home.join("Library/LaunchAgents/com.opensessionlog.osl-watch.plist");
        let existed = path.exists();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, render_launchd_plist(cfg))?;
        let uid = std::process::Command::new("id")
            .arg("-u")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .unwrap_or_else(|| "$(id -u)".to_string());
        if existed {
            println!(
                "launchctl kickstart -p gui/{}/com.opensessionlog.osl-watch",
                uid
            );
        } else {
            println!("launchctl bootstrap gui/{} {}", uid, path.display());
        }
        Ok(())
    }

    #[cfg(target_os = "macos")]
    pub fn remove_with_home(home: &Path) -> Result<()> {
        let path = home.join("Library/LaunchAgents/com.opensessionlog.osl-watch.plist");
        let uid = std::process::Command::new("id")
            .arg("-u")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .unwrap_or_else(|| "$(id -u)".to_string());
        if path.exists() {
            fs::remove_file(&path)?;
            println!("launchctl bootout gui/{}/com.opensessionlog.osl-watch", uid);
            Ok(())
        } else {
            println!("No autostart config found");
            Ok(())
        }
    }

    #[cfg(target_os = "windows")]
    pub fn install_with_home(cfg: &AutostartConfig, home: &Path) -> Result<()> {
        let dir = home.join(".opensessionlog");
        fs::create_dir_all(&dir)?;
        let path = dir.join("osl-watch.xml");
        fs::write(&path, render_schtasks_xml(cfg))?;
        println!(
            r#"schtasks /create /tn "OpenSessionLog Watch" /xml "{}" /f"#,
            path.display()
        );
        Ok(())
    }

    #[cfg(target_os = "windows")]
    pub fn remove_with_home(home: &Path) -> Result<()> {
        let path = home.join(".opensessionlog/osl-watch.xml");
        println!(r#"schtasks /delete /tn "OpenSessionLog Watch" /f"#);
        if path.exists() {
            fs::remove_file(&path)?;
        }
        Ok(())
    }

    #[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
    pub fn install_with_home(_cfg: &AutostartConfig, _home: &Path) -> Result<()> {
        Err(OslError::Usage(
            "autostart is not supported on this platform".into(),
        ))
    }

    #[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
    pub fn remove_with_home(_home: &Path) -> Result<()> {
        Err(OslError::Usage(
            "autostart is not supported on this platform".into(),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn config_new_resolves_exe() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        assert_eq!(cfg.osl_exe, std::env::current_exe().unwrap());
    }

    #[test]
    fn config_makes_vault_absolute() {
        let cfg = AutostartConfig::new(&[], Path::new("vault.sqlite")).unwrap();
        assert!(cfg.vault.is_absolute());
        assert!(cfg.vault.file_name().unwrap() == "vault.sqlite");
    }

    #[test]
    fn config_makes_paths_absolute() {
        let cfg = AutostartConfig::new(
            &[PathBuf::from("relative/path")],
            Path::new("/tmp/vault.sqlite"),
        )
        .unwrap();
        assert_eq!(cfg.paths.len(), 1);
        assert!(cfg.paths[0].is_absolute());
        assert!(cfg.paths[0].ends_with("relative/path"));
    }

    #[test]
    fn config_empty_paths_stay_empty() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        assert!(cfg.paths.is_empty());
    }

    #[test]
    fn config_uses_default_interval() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        assert_eq!(cfg.interval, DEFAULT_INTERVAL);
    }

    #[test]
    fn render_systemd_unit_has_header() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        let out = render_systemd_unit(&cfg);
        assert!(out.starts_with("# Generated by osl"));
    }

    #[test]
    fn render_systemd_unit_has_execstart() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        let out = render_systemd_unit(&cfg);
        assert!(out.contains("ExecStart="));
    }

    #[test]
    fn render_systemd_unit_no_paths_when_empty() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        let out = render_systemd_unit(&cfg);
        let exec_line = out.lines().find(|l| l.starts_with("ExecStart=")).unwrap();
        assert!(
            !exec_line.contains("/tmp/source"),
            "expected no source paths in ExecStart: {exec_line}"
        );
    }

    #[test]
    fn render_systemd_unit_embeds_explicit_paths() {
        let cfg = AutostartConfig::new(
            &[PathBuf::from("/tmp/source")],
            Path::new("/tmp/vault.sqlite"),
        )
        .unwrap();
        let out = render_systemd_unit(&cfg);
        assert!(out.contains("/tmp/source"));
    }

    #[test]
    fn render_systemd_unit_quotes_spaces() {
        let cfg = AutostartConfig::new(
            &[PathBuf::from("/tmp/my source")],
            Path::new("/tmp/vault.sqlite"),
        )
        .unwrap();
        let out = render_systemd_unit(&cfg);
        assert!(out.contains(r#""/tmp/my source""#));
    }

    #[test]
    fn render_launchd_plist_has_header() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        let out = render_launchd_plist(&cfg);
        assert!(out.contains("<!-- Generated by osl"));
    }

    #[test]
    fn render_schtasks_xml_has_header() {
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        let out = render_schtasks_xml(&cfg);
        assert!(out.contains("<!-- Generated by osl"));
    }

    #[test]
    fn xml_escape_escapes_special_chars() {
        let input = r#"&<>"'"#;
        let out = xml_escape(input);
        assert_eq!(out, "&amp;&lt;&gt;&quot;&apos;");
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn install_with_home_linux_writes_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let home = tmp.path();
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();
        install_with_home(&cfg, home).unwrap();

        let path = home.join(".config/systemd/user/osl-watch.service");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("ExecStart="));
        assert!(content.contains("--interval 60"));
        assert!(content.contains("--vault"));
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn install_with_home_linux_update_vs_create() {
        let tmp = tempfile::TempDir::new().unwrap();
        let home = tmp.path();
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();

        // First install
        install_with_home(&cfg, home).unwrap();
        let path = home.join(".config/systemd/user/osl-watch.service");
        assert!(path.exists());

        // Second install (update)
        install_with_home(&cfg, home).unwrap();
        assert!(path.exists());
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn remove_with_home_linux_no_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let home = tmp.path();
        remove_with_home(home).unwrap();
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn install_then_remove_roundtrip() {
        let tmp = tempfile::TempDir::new().unwrap();
        let home = tmp.path();
        let cfg = AutostartConfig::new(&[], Path::new("/tmp/vault.sqlite")).unwrap();

        install_with_home(&cfg, home).unwrap();
        let path = home.join(".config/systemd/user/osl-watch.service");
        assert!(path.exists());

        remove_with_home(home).unwrap();
        assert!(!path.exists());
    }
}
